finalP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainPage import views

handler404 = "mainPage.views.error404"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mainPage.urls")),
    path("pymes/", include("primeraPyme.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#configuarion necesaria para cargar imagenes

primeraPyme/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name="gestion"
urlpatterns = [
    #path("", views.pyme1, name="pyme1"),
    path("pyme<int:pk>", views.pyme1, name="pyme"),
    path("agregar/<int:pk>/", login_required(views.GuardarProducto.as_view()), name="agregarProducto"),
    path("producto/<int:pk>/", views.detalles, name="detalle"),#el <int:pk> sirve para decirle a la url que se espera un dato entero 
    #esto sirve para poder ver datos especificos de un campo en la bd
    path("agregarCarro/<int:producto_id>/", views.agregarCarro, name="agregarCarro"),
    path("eliminarCarro/<int:producto_id>/", views.eliminarCarro, name="eliminarCarro"),
    path("restarCarro/<int:producto_id>/", views.restarCarro, name="restarCarro"),
    path("vaciarCarro", views.vaciarCarro, name="vaciarCarro"),
    path("pedidos/", views.pedidos, name="pedido"),
    path("agregarPedido/", views.agregarPedido, name="agregarPedido"),
    path("historialpedido/", views.detallePedido, name="historial"),
    

]
   

mainPage/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class Usuarios(AbstractUser):
    rol = models.IntegerField(default=1) # 1 para usuarios 2 para propietarios y 3 para administradores
    
    class Meta:    
        verbose_name='Usuario'
        verbose_name_plural='Usuarios'
        db_table='usuarios'
    


class Propietarios(models.Model):
    datosPropietario = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    nombrePyme = models.CharField(max_length=30)
        
        
    class Meta:
        verbose_name='Propietario'
        verbose_name_plural='Propietarios'
        db_table='propietarios'


    
class Solicitudes(models.Model):
    
    fecha_de_solicitud = models.DateField(auto_now_add=True, null=True)
    nombre = models.CharField(max_length=20)
    apellidos = models.CharField(max_length=60)
    rut = models.CharField(max_length=12)
    categoria = models.CharField(max_length=60, default=None)
    nombrePyme = models.CharField(max_length=100)
    solicitud = models.CharField(max_length=500)
    imagen = models.ImageField(upload_to='logoPymesSoli', null=True)
    idSolicitante = models.IntegerField(null=True, default=None)
    
    class Meta:
        verbose_name='Solicitud'
        verbose_name_plural='Solicitudes'
        db_table='solicitudes'

class Pymes(models.Model):
    
    nombrePyme=models.CharField(max_length=30)
    direccion = models.CharField(max_length=60)
    categoria = models.CharField(max_length=20)
    propietario= models.ForeignKey(Propietarios,null=True,on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='logoPymes', null=True)
    
    def get_img_url(self):
        return self.logo.imagen.url
    
    class Meta:
        verbose_name='Pymes'
        verbose_name_plural='Pymes'
        db_table='pymes'
    



class Productos(models.Model):
    
    pymeAsociada= models.ForeignKey(Pymes,null=True, blank=True, on_delete=models.CASCADE)
    nombreProducto=models.CharField(max_length=35)
    descripcion=models.CharField(max_length=150)
    precio=models.DecimalField(max_digits=10, decimal_places=2)
    cantidad=models.IntegerField()
    imagen = models.ImageField(upload_to='imagenesT', null=True)
    
    class Meta:
        verbose_name='Producto'
        verbose_name_plural='Productos'
        db_table='productos'
    
    
    
class Pedido(models.Model):
    usuario = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Productos, through='ItemPedido')
    total = models.DecimalField(max_digits=10, decimal_places=2)
    creado_en = models.DateTimeField(auto_now_add=True)
    
    
    
    class Meta:
        verbose_name='Pedido'
        verbose_name_plural='Pedidos'
        db_table='pedidos'

    def __str__(self):
        return f"Pedido de {self.usuario.username} - {self.creado_en}"

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Productos, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.cantidad} x {self.producto.nombre} en {self.pedido}"
    
    class Meta:
        verbose_name='Detalle_Pedido'
        verbose_name_plural='Detalle_Pedidos'
        db_table='pedidos_detalle'
    

primeraPyme/forms.py
from django import forms
from mainPage.models import Productos


class ProductoFrom(forms.ModelForm):
    nombreProducto = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}), max_length=35)
    descripcion = forms.CharField(widget=forms.Textarea(attrs={"class":"form-control"}), max_length=250)
    cantidad = forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}))
    precio = forms.DecimalField(widget=forms.NumberInput(attrs={"class":"form-control"}), max_digits=10, decimal_places=2)
    imagen = forms.ImageField(label="Avatar", required=False, widget=forms.FileInput(attrs={"class":"form-control"}))
    
    class Meta:
        model = Productos
        fields = ['id', 'pymeAsociada', 'nombreProducto', 'descripcion','cantidad', 'precio', 'imagen' ]
        

primeraPyme/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from .forms import ProductoFrom
from django.views.generic import View
from django.http import HttpResponseRedirect
from mainPage.models import Usuarios,ItemPedido,Pedido,Productos, Propietarios, Pymes
from django.urls import reverse
from carro.carro import Carro
from carro.context_processor import total_carrito



# Create your views here.

#vista principal de la pyme
def pyme1(request, pk):
    pyme = get_object_or_404(Pymes, pk=pk)
    propietario = Propietarios.objects.all()
    productos = Productos.objects.all()
    data = { 'productos':productos, "pyme":pyme, "propie":propietario}
    return render(request, "primeraPyme/snakedreams.html",data)




#funcion basa en clases que permite mostrar y guardar el formulario para agregar productos
class GuardarProducto(View):
    def get(self, request, pk):
        pyme = get_object_or_404(Pymes, pk = pk)
        form = ProductoFrom()
        return render(request, "primeraPyme/add-producto.html", {
            "form": form
        })
        
        
        
    def post(self, request, pk):
        form = ProductoFrom(request.POST, request.FILES)
        
        if request.user.is_authenticated:
            userRol = request.user.rol
            pyme = get_object_or_404(Pymes, pk=pk)
            
            if form.is_valid():
                nombre = form.cleaned_data['nombreProducto']
                descripcion = form.cleaned_data['descripcion']
                cantidad = form.cleaned_data['cantidad']
                precio = form.cleaned_data['precio']
                imagen = form.cleaned_data['imagen']
                
                product = Productos(
                    nombreProducto=nombre,
                    descripcion=descripcion,
                    cantidad=cantidad, 
                    precio=precio, 
                    imagen=imagen,
                    pymeAsociada=pyme  # Asociamos directamente la instancia de Pymes
                )
                product.save()
                return redirect('main:main')
            
            # Si el formulario no es válido, manejar el caso
            data = {"user": userRol, "pyme": pyme, "form": form}
            return render(request, "primeraPyme/snakedreams.html", data)
        
        
#detalles de cada producto
def detalles(request, pk):
    pyme = Pymes.objects.all()
    producto = get_object_or_404(Productos, pk=pk)
    data = {'producto': producto, "pyme":pyme }
    return render(request, "primeraPyme/producto.html", data)


# carrito de compras 

def pedidos(request):
    
    total_carro = total_carrito(request)["total_carro"]
    contexto = {
        # Otros elementos del contexto
        'total_carro': total_carro,
    }
    return render(request, "primeraPyme/pedido.html", contexto)

def agregarCarro(request, producto_id):
    carro = Carro(request)
    producto = Productos.objects.get(id =producto_id)
    carro.agregar(producto)
    return redirect("main:main")

def eliminarCarro(request, producto_id):
    carro = Carro(request)
    producto = Productos.objects.get(id =producto_id)
    carro.remove(producto)
    return redirect("main:main")


def restarCarro(request, producto_id):
    carro = Carro(request)
    producto = Productos.objects.get(id =producto_id)
    carro.decrement(producto)
    return redirect("main:main")

def vaciarCarro(request):
    carro = Carro(request)
    carro.limpiar()
    return redirect("main:main")

def agregarPedido(request):
    carro = Carro(request)
# Recorrer la lista de productos en el carrito
    if request.user.is_authenticated:
        productos_en_carro = carro.carro.values()
        userid = request.user.id
        user = Usuarios.objects.get(id=userid)
        pedido = Pedido(usuario = user, 
                                total =0)
        if productos_en_carro:  
            for producto in productos_en_carro:
                idProducto = producto["producto_id"]
                produ = Productos.objects.get(id=idProducto)
                cantidad = producto["cantidad"]
                
                
                detailPedido = ItemPedido(pedido = pedido,
                                cantidad = cantidad,
                                producto = produ)
                pedido.save()
                detailPedido.save()
            return redirect("main:main")
        
    
def detallePedido(request):
    if request.user.is_authenticated:
        pedidos = Pedido.objects.all()
        data = {"pedidos":pedidos}
        return render(request, "primeraPyme/pedido-usuario.html", data)
    else:
        return render(request, "primeraPyme/pedido-usuario.html")

templates/primeraPyme/add-producto.html
{% extends "base/base.html" %}

{% block name %} agregar producto  {% endblock  %}

{% block content %}

<h1 class="ms-5">Agregar Producto</h1>
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <label for="id_nombreProducto" class="col-form-label">Nombre del Producto:</label>
            {{ form.nombreProducto }}
        </div>
        <div>
            <label for="id_descripcion" class="col-form-label">Descripción:</label>
            {{ form.descripcion }}
        </div>
        <div>
            <label for="id_descripcion" class="col-form-label">Cantidad:</label>
            {{ form.cantidad }}
        </div>
        <div>
            <label for="id_precio" class="col-form-label">Precio:</label>
            {{ form.precio }}
        </div>
        <div>
            <label for="id_imagen">Imagen:</label>
            {{ form.imagen }}
        </div>
        <br>
        <div class="modal-footer">
        <Button class="btn btn-primary">Agregar</Button>
        </div>
        
    </form>
    <br>
    
</div>

{% endblock content %}

templates/primeraPyme/pedido-usuario.html
{% extends "base/base.html" %}

{% block name %}
Historial Pedidos
{% endblock name %}

{% block title %}
<h1>Historial Pedidos</h1>
{% endblock title %}

{% block style %}
<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
    </style>
{% endblock  %}
{% block content %}
    <table>   
        <tr>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Estado</th>
        </tr>
        {% for pedido in pedidos %}
            {% if request.user.id == pedido.usuario_id %}
                {% for detalle in pedido.itempedido_set.all %}
                    <tr>
                        <td>{{ detalle.producto.nombreProducto }}</td>
                        <td>{{ detalle.cantidad }}</td>
                        <td>...</td>  {# Aquí deberías completar la información del estado #}
                    </tr>
                {% endfor %}
            {% endif %}
        {% empty %}
            <tr>
                <td colspan="3">No hay Pedidos Realizados</td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

templates/primeraPyme/pedido.html
<div class="alert alert-primary" role="alert">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="row" colspan="3" class="text-center">Carro</th>
            </tr>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Precio</th>
                <th scope="col">Cantidad</th>
            </tr>
        </thead>
        <tbody>
            {% if request.session.carro.items %}
                {% for key, value in request.session.carro.items %}
                    <tr>
                        <td>{{ value.nombreProducto }}</td>
                        <td>{{ value.precio }}</td>
                        <td>
                            {{ value.cantidad }}
                            <a href="{% url 'gestion:agregarCarro' value.producto_id %}" class="btn btn-dark badge-dark">+</a>
                            <a href="{% url 'gestion:restarCarro' value.producto_id %}" class="btn btn-dark badge-dark">-</a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3">
                        <div class="alert alert-danger text-center">Sin Productos</div>
                    </td>
                </tr>
            {% endif %}
            <tr>
                <th scope="row">Total:</th>
                <td colspan="2">$ {{ total_carro }}</td>
            </tr>
        </tbody>
    </table>
    <a href="{% url 'gestion:vaciarCarro' %}" class="btn btn-danger">Limpiar</a>
    <a href="{% url 'gestion:agregarPedido' %}" class="btn btn-danger">Guardar</a>
</div>

templates/primeraPyme/producto.html
{% extends "base/base.html" %}
{% load static %}

{% block name %} producto {% endblock  %}



{% block title %}

{% for py in pyme %}

{% if py.id == producto.pymeAsociada_id %}
<img src="{{ py.imagen.url }}" height="3%" width="3%" > <h1>{{py.nombrePyme}}</h1>
{% endif %}

{% endfor %}

{% endblock %}




{% block content %}

<img  src="{{ producto.imagen.url }}" width="200px"  height="200px" alt="Imagen del producto">
<h1>{{producto.nombreProducto}}</h1>
<h1>{{producto.descripcion}}</h1>
<h1>{{producto.precio}}</h1>

<a href="{% url 'gestion:pyme' producto.pymeAsociada_id %}" class="btn btn-danger">Volver</a>
{% endblock  %}

templates/primeraPyme/snakedreams.html
{% extends "base/base.html" %}
{% load static %}

{% block name %} tienda  {% endblock  %}

{% block title %}<img src="{{ pyme.imagen.url }}" height="3%" width="3%" > <h1>{{pyme.nombrePyme}}</h1>{% endblock %}


{% block content %}

<div class="row">
    
    {% for producto in productos %}
    {% if producto.pymeAsociada_id == pyme.id %}
    <a href="{% url 'gestion:detalle' producto.id %}" style="text-decoration: none; width:auto">
    <div class="col-md-3">
    <div class="card" style="width: 15rem;">
        {% if producto.imagen %}
    <img class="card-img-top " src="{{ producto.imagen.url }}" width="18rem"  height="250rem" alt="Imagen del producto">
    {% else %}
            <p>No hay imagen disponible</p>
            {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ producto.nombreProducto }}</h5>
            <p class="card-text">{{ producto.descripcion }}</p>
            <p class="card-text">Precio: {{ producto.precio }}</p> 
            <a class="btn btn-primary" href="{% url 'gestion:agregarCarro' producto.id%}" >Agregar Al Pedido</a>
        </div>
    </div>
</div>
</a>

{% endif %}
    {% endfor %}


    <div class="col-4">
        
    </div>
    
</div>
</a>
{% for p in propie  %}
{% if user.rol == 2 and pyme.propietario_id == p.id and p.datosPropietario_id == user.id %}
<div class="modal-footer" >
    <a class="btn btn-primary" href="{% url 'gestion:agregarProducto' pk=pyme.id %}">Agregar un Producto</a>
    </div>
{% endif %}

{% endfor %}

{% endblock  %}