finalP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainPage import views

handler404 = "mainPage.views.error404"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mainPage.urls")),
    path("pymes/", include("primeraPyme.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#configuarion necesaria para cargar imagenes

mainPage/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView

app_name ="main"#aqui se le regitra un nombre globlal a esta seccion de urls en la aplicacion para poder llamarla 
                #en otro archivo de manera especifica
urlpatterns = [
    path("", views.main, name="main"),
    path("registrar/", views.registrar, name="register"),
    path('login/', views.login.as_view(template_name='mainPage/login.html', success_url='/account/'), name="login"),#aqui llamamos a la vista login default de django y a la logout
    path("logout/", LogoutView.as_view(template_name='mainPage/logout.html',next_page='/login/'), name="logout"),
    path("account/", views.cuentaUser, name="account"),
    path("solicitud/", login_required(views.solicitud), name="solicitud"),
    path("adminsolicitud/", login_required(views.solicitudAdmin, login_url="/login/"), name="solicitudAdmin"),
    path("borrar/<int:pk>/", login_required(views.rechazar), name="eliminar"),
    path("solidetail/<int:pk>/", login_required(views.soliDetalles), name="solidetail"),
    path("aceptar/<int:pk>/", login_required(views.aceptar), name="aceptar"),
    
]
#la funcion login_required agrega la seguridad de que el usuario deba estar logeado para poder ingresar a esa url

primeraPyme/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name="gestion"
urlpatterns = [
    #path("", views.pyme1, name="pyme1"),
    path("pyme<int:pk>", views.pyme1, name="pyme"),
    path("agregar/<int:pk>/", login_required(views.GuardarProducto.as_view()), name="agregarProducto"),
    path("producto/<int:pk>/", views.detalles, name="detalle"),#el <int:pk> sirve para decirle a la url que se espera un dato entero 
    #esto sirve para poder ver datos especificos de un campo en la bd
    path("agregarCarro/<int:producto_id>/", views.agregarCarro, name="agregarCarro"),
    path("eliminarCarro/<int:producto_id>/", views.eliminarCarro, name="eliminarCarro"),
    path("restarCarro/<int:producto_id>/", views.restarCarro, name="restarCarro"),
    path("vaciarCarro", views.vaciarCarro, name="vaciarCarro"),
    path("pedidos/", views.pedidos, name="pedido"),
    path("agregarPedido/", views.agregarPedido, name="agregarPedido"),
    path("historialpedido/", views.detallePedido, name="historial"),
    

]
   

templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block name%} {% endblock%}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sidebars.css' %}">
    {% block style %}
    
    {% endblock  %}

    
    

</head>
<body>


    <div class="">
        <!--
          inicio del header
        -->
        <header class="py-3 mb-3 border-bottom">
          <div class="container-fluid d-flex align-items-center justify-content-between">
              <div class="dropdown col-0" style="margin-left: 20px;">
                  <a href="#" class="d-flex align-items-center link-body-emphasis text-decoration-none" data-bs-toggle="dropdown" aria-expanded="false">
                      <strong>Categorias</strong>
                  </a>
                  <ul class="dropdown-menu text-small shadow">
                      <li style="text-align: center; background-color: grey;"><h6>Categorias</h6></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Perfumería</a></li>
                      <li><a class="dropdown-item" href="#">Vestuario</a></li>
                      <li><a class="dropdown-item" href="#">Hogar</a></li>
                      <li><a class="dropdown-item" href="#">Alimentación</a></li>
                      <li><a class="dropdown-item" href="#">Varios</a></li>
                  </ul>
              </div>
            {% block title %}  {% endblock %}
            

          <div class="col-md-3 mb-2 mb-md-0">
            <a  class="d-inline-flex link-body-emphasis text-decoration-none">
              <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>
          </div>
         
          <div class="col-auto text-end"> 

            <a href="/" type="button" class="btn me-2">
              <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5Z"/>
              </svg>
            </a>

           
            <a href="{% url 'gestion:historial' %}" type="button" class="btn me-2">
              <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-bag-dash-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0zM6 9.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1H6z"/>
              </svg>
            </a>

            

            {% if request.user.rol == 3 %}
            <a href="{% url 'main:solicitudAdmin' %}" type="button" class="btn me-2">
              <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-clipboard-plus-fill" viewBox="0 0 16 16">
                <path d="M6.5 0A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0zm3 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5z"/>
                <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1A2.5 2.5 0 0 1 9.5 5h-3A2.5 2.5 0 0 1 4 2.5zm4.5 6V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5a.5.5 0 0 1 1 0"/>
              </svg>
            </a>
            {% endif %}


          </div>

          <div class="dropdown">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-cart-dash-fill" viewBox="0 0 16 16">
                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M6.5 7h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1"/>
              </svg>
            </a>
            <ul class="dropdown-menu text-small shadow">
              <li>{% include "primeraPyme/pedido.html" %}</li>
            </ul>
          </div>

            <div class="col-0" style="margin-right: 20px;">
              <div class="dropdown">
                  <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="icon-white" viewBox="0 0 16 16">
                          <path fill-rule="evenodd" d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0v-2z"/>
                          <path fill-rule="evenodd" d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                        </svg>
                  </a>
                  <ul class="dropdown-menu text-small shadow">
                    <li><a class="dropdown-item" href="/account/">Mi Cuenta</a></li>
                      <li><a class="dropdown-item" href="/login/">Iniciar Sesion</a></li>
                      <li><a class="dropdown-item" href="/registrar/">Registrarse</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="/solicitud/">Solicitud Registro Pymes</a></li>
                      
                  </ul>
              </div>
            </div>
          </div>
        </header>
    </div>
    


    {% if messages  %}
    {% for message in  messages %}
    <div class="notification {{message.tags}}" >
      {{message}} 

    </div>
    
    {% endfor %}
    
    {% endif %}
        <!--fin del header-->

    
     <main class="container">
      {% block content %}
        <!-- Aqui el contenido de la Pagina-->

        {%endblock%}
     </main>
     

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/sidebars.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/base/error404.html
<!DOCTYPE html>
<html>
<head>
    <title>Error 404</title>
</head>
<body>
    <h1>Lo sentimos, la página que estás buscando no se ha encontrado.</h1>
</body>
</html>