finalP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainPage import views

handler404 = "mainPage.views.error404"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mainPage.urls")),
    path("pymes/", include("primeraPyme.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#configuarion necesaria para cargar imagenes

mainPage/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView

app_name ="main"#aqui se le regitra un nombre globlal a esta seccion de urls en la aplicacion para poder llamarla 
                #en otro archivo de manera especifica
urlpatterns = [
    path("", views.main, name="main"),
    path("registrar/", views.registrar, name="register"),
    path('login/', views.login.as_view(template_name='mainPage/login.html', success_url='/account/'), name="login"),#aqui llamamos a la vista login default de django y a la logout
    path("logout/", LogoutView.as_view(template_name='mainPage/logout.html',next_page='/login/'), name="logout"),
    path("account/", views.cuentaUser, name="account"),
    path("solicitud/", login_required(views.solicitud), name="solicitud"),
    path("adminsolicitud/", login_required(views.solicitudAdmin, login_url="/login/"), name="solicitudAdmin"),
    path("borrar/<int:pk>/", login_required(views.rechazar), name="eliminar"),
    path("solidetail/<int:pk>/", login_required(views.soliDetalles), name="solidetail"),
    path("aceptar/<int:pk>/", login_required(views.aceptar), name="aceptar"),
    
]
#la funcion login_required agrega la seguridad de que el usuario deba estar logeado para poder ingresar a esa url

primeraPyme/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name="gestion"
urlpatterns = [
    #path("", views.pyme1, name="pyme1"),
    path("pyme<int:pk>", views.pyme1, name="pyme"),
    path("agregar/<int:pk>/", login_required(views.GuardarProducto.as_view()), name="agregarProducto"),
    path("producto/<int:pk>/", views.detalles, name="detalle"),#el <int:pk> sirve para decirle a la url que se espera un dato entero 
    #esto sirve para poder ver datos especificos de un campo en la bd
    path("agregarCarro/<int:producto_id>/", views.agregarCarro, name="agregarCarro"),
    path("eliminarCarro/<int:producto_id>/", views.eliminarCarro, name="eliminarCarro"),
    path("restarCarro/<int:producto_id>/", views.restarCarro, name="restarCarro"),
    path("vaciarCarro", views.vaciarCarro, name="vaciarCarro"),
    path("pedidos/", views.pedidos, name="pedido"),
    path("agregarPedido/", views.agregarPedido, name="agregarPedido"),
    path("historialpedido/", views.detallePedido, name="historial"),
    

]
   

mainPage/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class Usuarios(AbstractUser):
    rol = models.IntegerField(default=1) # 1 para usuarios 2 para propietarios y 3 para administradores
    
    class Meta:    
        verbose_name='Usuario'
        verbose_name_plural='Usuarios'
        db_table='usuarios'
    


class Propietarios(models.Model):
    datosPropietario = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    nombrePyme = models.CharField(max_length=30)
        
        
    class Meta:
        verbose_name='Propietario'
        verbose_name_plural='Propietarios'
        db_table='propietarios'


    
class Solicitudes(models.Model):
    
    fecha_de_solicitud = models.DateField(auto_now_add=True, null=True)
    nombre = models.CharField(max_length=20)
    apellidos = models.CharField(max_length=60)
    rut = models.CharField(max_length=12)
    categoria = models.CharField(max_length=60, default=None)
    nombrePyme = models.CharField(max_length=100)
    solicitud = models.CharField(max_length=500)
    imagen = models.ImageField(upload_to='logoPymesSoli', null=True)
    idSolicitante = models.IntegerField(null=True, default=None)
    
    class Meta:
        verbose_name='Solicitud'
        verbose_name_plural='Solicitudes'
        db_table='solicitudes'

class Pymes(models.Model):
    
    nombrePyme=models.CharField(max_length=30)
    direccion = models.CharField(max_length=60)
    categoria = models.CharField(max_length=20)
    propietario= models.ForeignKey(Propietarios,null=True,on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='logoPymes', null=True)
    
    def get_img_url(self):
        return self.logo.imagen.url
    
    class Meta:
        verbose_name='Pymes'
        verbose_name_plural='Pymes'
        db_table='pymes'
    



class Productos(models.Model):
    
    pymeAsociada= models.ForeignKey(Pymes,null=True, blank=True, on_delete=models.CASCADE)
    nombreProducto=models.CharField(max_length=35)
    descripcion=models.CharField(max_length=150)
    precio=models.DecimalField(max_digits=10, decimal_places=2)
    cantidad=models.IntegerField()
    imagen = models.ImageField(upload_to='imagenesT', null=True)
    
    class Meta:
        verbose_name='Producto'
        verbose_name_plural='Productos'
        db_table='productos'
    
    
    
class Pedido(models.Model):
    usuario = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    productos = models.ManyToManyField(Productos, through='ItemPedido')
    total = models.DecimalField(max_digits=10, decimal_places=2)
    creado_en = models.DateTimeField(auto_now_add=True)
    
    
    
    class Meta:
        verbose_name='Pedido'
        verbose_name_plural='Pedidos'
        db_table='pedidos'

    def __str__(self):
        return f"Pedido de {self.usuario.username} - {self.creado_en}"

class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto = models.ForeignKey(Productos, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.cantidad} x {self.producto.nombre} en {self.pedido}"
    
    class Meta:
        verbose_name='Detalle_Pedido'
        verbose_name_plural='Detalle_Pedidos'
        db_table='pedidos_detalle'
    

mainPage/forms.py
from django import forms
from .models import Usuarios, Solicitudes
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm



#este formulario cambia el formulario default de registro en django
class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class":"form-control","placeholder":"Ingrese su Email"}))
    username = forms.CharField(label='Nombre de usuario', widget=forms.TextInput(attrs={"class":"form-control","placeholder":"Ingrese su Nombre de Usuario"}))
    first_name = forms.CharField(label='Nombre', widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Ingrese su Nombre"}))
    last_name = forms.CharField(label='Apellidos', widget=forms.TextInput(attrs={"class":"form-control","placeholder":"Ingrese su Apellido"}))
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Ingrese su Contraseña"}))
    password2 = forms.CharField(label='Confirmar Contraseña', widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Repetir Contraseña"}))
    
    class Meta:
        model = Usuarios
        fields = ['username','first_name','last_name',  'email', ] 
        help_texts = {k:"" for k in fields}



#formulario para el usuario que desee solicitar la adicion de su pyme en la pagina
class AddPymeForm(forms.ModelForm):
    nombre = forms.CharField(label='Nombre',widget=forms.TextInput(attrs={"class":"form-control"}), max_length=35)
    apellidos = forms.CharField(label='Apellidos', widget=forms.TextInput(attrs={"class":"form-control"}), max_length=35)
    rut = forms.CharField(label='Rut Empresa', widget=forms.TextInput(attrs={"class":"form-control"}), max_length=12)
    nombrePyme = forms.CharField(label='Nombre de su Pyme', widget=forms.TextInput(attrs={"class":"form-control"}), max_length=35)
    categoria = forms.CharField(label='Categoria de su Pyme', widget=forms.TextInput(attrs={"class":"form-control"}), max_length=35)
    solicitud = forms.CharField(label='Descripcion de solicitud' ,widget=forms.Textarea(attrs={"class":"form-control"}), max_length=250)
    imagen = forms.ImageField(label="Logo de su Pyme", required=False, widget=forms.FileInput(attrs={"class":"form-control"}))
    
    class Meta:
        model = Solicitudes
        fields = ['id','nombre','apellidos','rut',  'nombrePyme', 'categoria','solicitud', 'imagen'] 
        


#cambios en el formulario del login default de django (más que nada diseño)
class Login(AuthenticationForm):
    username = forms.CharField(label='Nombre de Usuario',widget=forms.TextInput(attrs={"class":"form-control","placeholder":"Ingrese su Nombre de Usuario"}), max_length=15)
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Ingrese su Contraseña"}))
    
    class Meta:
        
        fields = ['username','password'] 

mainPage/views.py
from django.shortcuts import render, redirect, get_object_or_404
from templates import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import CustomUserCreationForm, AddPymeForm, Login
from django.contrib.auth.decorators import login_required
from .models import Usuarios, Pymes, Solicitudes, Propietarios
from django.contrib.auth.views import LoginView

# Create your views here.

#funcion de la vista principal en el cual se muestra con un for luego en su template y se le pasa la variable del usuario logeado 
#para reconocer su rol
def main(request):
    pymes = Pymes.objects.all()
    if request.user.is_authenticated:
        user = request.user.rol
        data = { "u":user, "pymes":pymes}
        return render(request, "mainPage/main.html", data)
    else:
        data = { "pymes":pymes}
        return render(request, "mainPage/main.html", data)

#funcion para registrar un usuario y guardarlo en la base de datos 
def registrar(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)#aqui llamamos al formulario para el registro de usuarios
        if form.is_valid():
            user = form.save() 
            username = form.cleaned_data['username']
            messages.success(request, f'Usuario {username} Registrado')#aqui se muestra un mensaje al usuario de que el usuario fue registrado con exito
            return redirect('main:main')
    else:
        form = CustomUserCreationForm()
    context = {'form': form}
    return render(request, 'mainPage/register.html', context)


#funcion para la pagina del "perfil de usuario"
def cuentaUser(request):
    if request.user.is_authenticated:
        nameUser = request.user.first_name
        lastName = request.user.last_name
        email = request.user.email
        data = {"nombre": nameUser,"apellido": lastName , "email":email}
        return render(request, 'mainPage/users.html', data)
    else:
        
        return redirect('main:login')
    

#esta funcion aun no esta clara si se utilizara, pero genera un nombre unico para los archivos subidos
def generar_nombre_unico(nombre_original):
    import uuid
    extension = nombre_original.split('.')[-1]
    nombre_unico = f"{uuid.uuid4().hex}.{extension}"
    return nombre_unico


#solicitud del usuario para agregar su pyme a la pagina  
def solicitud(request):
    if request.method == 'POST':
        form = AddPymeForm(request.POST, request.FILES)
        if form.is_valid():
            #todas estas lineas se realizan para obtener la id del usuario registrado y almacenarlo, sin esto no se guardaba la id
            rut = form.cleaned_data['rut']
            fecha_solicitud = request.POST.get('fecha_de_solicitud')
            nombre = request.POST.get('nombre')
            apellidos = request.POST.get('apellidos')
            rut = request.POST.get('rut')
            categoria = request.POST.get('categoria')
            nombre_pyme = request.POST.get('nombrePyme')
            solicitud = request.POST.get('solicitud')
            imagen = request.FILES.get('imagen')
            idUser = request.user.id
            s = Solicitudes(fecha_de_solicitud=fecha_solicitud, nombre=nombre, apellidos=apellidos, 
                                      rut=rut, categoria=categoria, nombrePyme=nombre_pyme, solicitud=solicitud,
                                      imagen=imagen, idSolicitante=idUser)
            s.save()
            messages.success(request, f'Solicitud Enviada')
            return redirect('main:main')
        
    else:
        form = AddPymeForm()
    context = {'form': form}
    return render(request, 'mainPage/add-pyme.html', context)

#esta funcion muestra la lista de solicitudes enviadas 
def solicitudAdmin(request):
    soli = Solicitudes.objects.all()
    data = {'solicitudes':soli,}
    return render(request, "mainPage/solicitudes.html", data)


#funcion que rechaza la solictud
def rechazar(request,pk):
    soli = get_object_or_404(Solicitudes, pk=pk)
    soli.delete()
    return redirect("main:solicitudAdmin")

#funcion para aceptar una solictud que guarda los datos del solicitante y realiza el flujo principal solicitado 
#toma los datos enviados en la solicitud y los del solicitante luego crea una pyme en la base de datos y un propietario 
#tambien cambia su rol para poder agregar productos en su pyme
def aceptar(request,pk):    
    soli = get_object_or_404(Solicitudes, pk=pk)
    if request.user.is_authenticated:
        guardarUsuario = Propietarios(nombrePyme = soli.nombrePyme, datosPropietario_id = soli.idSolicitante)
        guardarUsuario.save()
        usuario = get_object_or_404(Usuarios, id=soli.idSolicitante)
        rolAdmin = 2
        usuario.rol = rolAdmin
        usuario.save()
        guardar = Pymes(nombrePyme=soli.nombrePyme, categoria=soli.categoria, imagen=soli.imagen, propietario_id = guardarUsuario.id)
        guardar.save()
        soli.delete()
        return redirect("main:solicitudAdmin")

#funcion para el boton que permite una vista completa de la solicitud
def soliDetalles(request, pk):
    solicitudes = get_object_or_404(Solicitudes, pk=pk)
   
    return render(request, "mainPage/detallesSolicitudes.html", {'soli': solicitudes})

#aplicar cambios de diseño en el login view
class login(LoginView):
    form_class = Login 
    template_name = 'mainPage/login.html'  

    # agregar lógica personalizada para el inicio de sesión
    def form_valid(self, form):
        # Realizar acciones personalizadas aquí si el formulario es válido
        return super().form_valid(form)

    def form_invalid(self, form):
        # Realizar acciones personalizadas aquí si el formulario es inválido
        return super().form_invalid(form)
    
    

#genera un archivo diferente para el error default 404 de django 
def error404(request, exception):
    return render(request, '/error404.html', status=404)

templates/mainPage/add-pyme.html
{% extends "base/base.html" %}

{% block name %} Solicitud {% endblock  %}

{% block title %}
<h1>Solicitud para Añadir Tu Pyme</h1>
{% endblock  %}


{% block content %}
<form class= "form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button  class="btn btn-primary">Enviar</button>
</form>
{% endblock  %}

templates/mainPage/detallesSolicitudes.html
{% extends "base/base.html" %}

{% block name %} Detalles de solicitud {% endblock  %}

{% block title %}

{% endblock  %}


{% block content %}
 
<ul>
    <li>Nombre De la Pyme: {{soli.nombrePyme}}</li>
    <li>Nombre del Dueño: {{soli.nombre}} {{soli.apellidos}} </li>
    <li>Fecha De Solicitud: {{soli.fecha_de_solicitud}}</li>
    <li>Rut del Solicitante: {{soli.rut}}</li>
</ul>
<h5>Solicitud: </h5>
<p>{{soli.solicitud}}</p>

<a href="{% url 'main:eliminar' soli.id %}" class="btn btn-danger" >Rechazar</a>

<a href="{% url 'main:aceptar' soli.id %}" class="btn btn-success" >Aceptar</a>
{% endblock  %}

templates/mainPage/login.html
{% extends "base/base.html" %}

{% block name %} Login {% endblock  %}

{% block title %}
<h1>Login</h1>
{% endblock  %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center" style="min-height: 100vh; margin-top: -150px;">
        <div class="col-md-6">
            <div class="card" style="transition:none; transform:none">
                <div class="card-header">Inicio de sesión</div>
                <div class="card-body">

<form class="form-signin" method="post"> 
    {% csrf_token %}
    {{form.as_p}}

     <button class="btn btn-primary" type="button submit">Iniciar Sesion</button>
    </form>
        <p>No tienes una cuenta, Registrate <a href="{% url 'main:register' %}">Aqui</a></p>


</div>
</div>
</div>
</div>


   
{% endblock  %}

templates/mainPage/logout.html
{% extends "base/base.html" %}

{% block title %}
<h1>Logout</h1>
{% endblock  %}

{% block content %}
    
<form class="form" method="post"> 
   
{% endblock  %}

templates/mainPage/main.html
{% extends "base/base.html" %}
{% load static %}

{% block name %} Pymes {% endblock  %}


{%block title%}<h1>Pyme's</h1>{%endblock%}

{%block content%}


<div class="row">
    {% for pyme in pymes  %}
    <div class="col-lg-3">
        <div class="card " style=" width:20rem; height:31rem;">
            <img src="{{ pyme.imagen.url }}" class="card-img-top" height="100%" width="100%">
            <div class="card-body">
                <h4 class="card-title text-center">{{ pyme.nombrePyme }}</h4>
                <br>
                <a href="{% url 'gestion:pyme' pyme.id %}" class="btn btn-primary boton-card ">Visitar</a>
            </div>
        </div>
    </div>
    {% endfor %}

    

{%endblock%}

templates/mainPage/register.html
{% extends "base/base.html" %}

{% block name %} Registrar {% endblock  %}


{% block title %}
<h1>Registrarse</h1>
{% endblock  %}

{% block content %}


<div class="container mt-5">
    <div class="row justify-content-center align-items-center" style="min-height: 100vh; margin-top: -150px;">
        <div class="col-md-6">
            <div class="card" style="transition:none; transform:none ">
                <div class="card-header">Registro</div>
                <div class="card-body">    
                    <form class="form" method="post"> 

                        {% csrf_token %}
                        {{form.as_p }}

                        <button class="btn btn-primary" type="button submit">Registrar</button>
                    </form>
                    <p>Ya tienes una Cuenta? Ingresa <a href="{% url 'main:login' %}">Aqui</a></p>


                </div>
                </div>
        </div>
</div>

{% endblock  %}

templates/mainPage/solicitudes.html
{% extends "base/base.html" %}

{% block name %} Solicitudes {% endblock  %}

{% block style %}
<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
    </style>
{% endblock  %}

{% block title %}
<h1>solicitudes </h1>
{% endblock  %}


{% block content %}
    {% if request.user.rol == 3 %}
        <table>
            <tr>
                <th>fecha de solicitud</th>
                <th>nombre</th>
                <th>apellido</th>
                <th>Rut Empresa</th>
                <th>nombre Pyme</th>
                <th>solicitud</th>
            </tr>
            {% for soli in solicitudes %}
                <tr>
                    <td>{{ soli.fecha_de_solicitud }}</td>
                    <td>{{ soli.nombre }}</td>
                    <td>{{ soli.apellidos }}</td>
                    <td>{{ soli.rut }}</td>
                    <td>{{ soli.nombrePyme }}</td>
                    <td>{{ soli.solicitud }}</td>
                    <td><a href="{% url 'main:solidetail' soli.id %}"><button class="btn btn-light">Ver solicitud</button></a></td>
                </tr>
            {% endfor %}
        </table>
        {% else %}
        <h1 class="text-align-center d-flex justify-content-center">Error 404</h1>
    {% endif %}
{% endblock %}

templates/mainPage/users.html
{% extends "base/base.html" %}

{% block name %} Mi Cuenta {% endblock  %}

{% block title %}
<h1>Mi Cuenta</h1>
{% endblock  %}


{% block style %}
<style>
    .cuentaUser{
        height: 100%;
        width: 100%;
        border-top: 5px solid;

    }
    .diseUser{
        height: 100%;
        width: 98%;
        border: 5px solid;

    }
    h2{
        margin-bottom: 20px;
        margin-top: 20px;
    }
    </style>
   
   
{% endblock  %}


{% block content %}

<div class="diseUser">
    <h1>Mi Cuenta</h1>
    <div class="cuentaUser">
        <div style="margin: 20px;">
            <h2>Nombre</h2>
            <h5>{{ nombre }}</h5>

            <h2>Apellido</h2>
            <h5>{{ apellido }}</h5>

            <h2>Email</h2>
            <h5>{{ email }}</h5>
        </div>
        <div class="modal-footer">
            <a style="height: 2.5rem; width: 7rem; margin: 20px;" class="btn btn-dark" href="{% url 'main:logout' %}">Salir</a>
        </div>
    </div>
</div>


{% endblock  %}